/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
  }
}
